apiVersion: v1
kind: Endpoints
metadata:
  name: localstack
  namespace: default
subsets:
- addresses:
  - ip: 172.20.0.2
  ports:
  - port: 4566
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: default
spec:
  ports:
  - port: 4566
    targetPort: 4566
    protocol: TCP
